# syntax=docker/dockerfile:1

FROM unity6-license-helper:6000.0.46f1-base

USER root
SHELL ["/bin/bash", "-euxo", "pipefail", "-c"]

ENV CHROME_FLAGS="--no-sandbox --no-first-run --no-default-browser-check --disable-dev-shm-usage" \
    BROWSER=/usr/local/bin/container-browser

RUN if [ ! -f /opt/google/chrome/google-chrome.real ]; then \
        mv /opt/google/chrome/google-chrome /opt/google/chrome/google-chrome.real; \
    fi \
    && printf '#!/usr/bin/env bash\nexec /opt/google/chrome/google-chrome.real ${CHROME_FLAGS:-} "$@"\n' > /opt/google/chrome/google-chrome \
    && chmod 0755 /opt/google/chrome/google-chrome \
    && printf '#!/usr/bin/env bash\nexec google-chrome-stable ${CHROME_FLAGS:-} "$@"\n' > /usr/local/bin/container-browser \
    && chmod 0755 /usr/local/bin/container-browser \
    && printf '%s\n' \
        '[Desktop Entry]' \
        'Name=Container Browser' \
        'Exec=/usr/local/bin/container-browser %U' \
        'Type=Application' \
        'Terminal=false' \
        'MimeType=text/html;x-scheme-handler/http;x-scheme-handler/https;x-scheme-handler/unityhub;' \
        > /usr/share/applications/container-browser.desktop \
    && update-alternatives --install /usr/bin/x-www-browser x-www-browser /usr/local/bin/container-browser 200 \
    && update-alternatives --set x-www-browser /usr/local/bin/container-browser

COPY scripts/start-unity-hub-vnc.sh /usr/local/bin/start-unity-hub-vnc.sh
RUN chmod 0755 /usr/local/bin/start-unity-hub-vnc.sh

ENTRYPOINT ["/usr/local/bin/start-unity-hub-vnc.sh"]
